theme: mbghi
title: Seyed Mostafa Baghi
description: Welcome to my GitHub profile! I'm passionate about programming, web development, and financial markets, especially Forex and cryptocurrency trading.
